Feat/select
bricksandbraces/designsystem pull request #102
Opened 2021-09-07 19:07 UTC by klonsian

2021-09-08 10:01 UTC, hendriku requested changes

2021-09-08 10:04 UTC, hendriku commented on src/components/Select/Select.tsx
> +          {children}
Hier muss natürlich mapping gemacht werden wie beim Dropdown auch. Mach ich dann auch mit

2021-09-08 14:25 UTC, klonsian commented on src/components/Select/Select.tsx
> +          <option value="">{title}</option>
passt, du bist der technikboss. :D

2021-09-09 07:49 UTC, hendriku approved these changes

2021-09-09 09:06 UTC, merged