feat: intro
bricksandbraces/designsystem pull request #134
Opened 2021-09-23 18:11 UTC by klonsian

2021-09-24 15:06 UTC, hendriku requested changes

2021-09-24 15:06 UTC, hendriku commented on src/components/Intro/Intro.stories.tsx
> +export default { title: "Welcome", decorators: [withKnobs] };
```suggestion
export default { title: "Intro", decorators: [withKnobs] };
```

2021-09-24 15:06 UTC, hendriku commented on src/components/Intro/Intro.stories.tsx
> +export const Welcome = () => {
```suggestion
export const Intro = () => {
```

2021-09-24 15:06 UTC, hendriku commented on src/components/Intro/Intro.tsx
> +      style={{
Ich würde sagen das muss in eine css-Klasse? backgroundImage evtl steuerbar machen über eine Property?

2021-09-24 15:06 UTC, hendriku commented on src/components/Intro/Intro.tsx
> +      <div style={{ padding: "32px" }}>
Das in eine CSS Klasse auslagern

2021-09-24 15:06 UTC, hendriku commented on src/components/Intro/Intro.tsx
> +          Design System
Das in eine Property auslagern

2021-09-24 15:06 UTC, hendriku commented on src/components/Intro/Intro.tsx
> +          v.0.0.1 React Storybook
Das auch in eine Property auslagern

2021-09-26 08:12 UTC, hendriku commented on src/components/Intro/Intro.tsx
> +      style={{
du kannst für sowas die storybook.css nehmen (just FYI)

2021-09-26 09:44 UTC, klonsian commented on src/components/Intro/Intro.stories.tsx
> +export default { title: "Welcome", decorators: [withKnobs] };
den kann ich nicht ohne errors fixen.

2021-09-26 13:23 UTC, merged