feat: footer
bricksandbraces/designsystem pull request #29
Opened 2021-07-23 13:48 UTC by klonsian

2021-07-25 18:31 UTC, hendriku commented on src/components/Footer/Footer.tsx
> +                  <Link href={descriptionLink.href} inline>
Innerhalb von Typography können wir derzeit keine Link Komponente verwenden das gibt einen error in der Konsole... weil link ein div UND ein p produziert und typography ggf ein p ist. Da Dürfen keine p's rein

2021-07-28 19:58 UTC, hendriku requested changes

2021-07-28 19:58 UTC, hendriku commented on src/components/Footer/Footer.tsx
> +              type="paragraph"
```suggestion
              type="text"
```

2021-07-28 20:35 UTC, klonsian reviewed
(Y)

2021-07-28 20:35 UTC, merged