Feat/cookiemodal
bricksandbraces/designsystem pull request #34
Opened 2021-07-29 20:52 UTC by klonsian

2021-07-30 07:25 UTC, hendriku commented on src/components/Modal/Modal.pcss
> +  content: "";
Wofür brauchen wir das `content` style Attribut? 🤔 💭

2021-07-30 07:26 UTC, hendriku commented on src/components/Modal/Modal.pcss
> +    height: 100%;
Hier könnte man Mal Gebrauch von unserem geilen Sizing package machen. 😏 https://github.com/postcss/postcss-size

2021-07-30 07:28 UTC, hendriku commented on src/components/Modal/Modal.pcss
> +  @media screen and (max-width: $breakpoint-md) {
Warum brauchen wir die `screen` media condition?
I mean, unsere Website wird sowieso nicht gut printbar sein denke ich :D

2021-07-30 07:31 UTC, hendriku requested changes

2021-07-30 07:31 UTC, hendriku commented on src/components/Modal/ModalFooter.tsx
> +      {((secondaryLabel && primaryLabel) || primaryLabel) && (
Um diese kryptische condition zu umgehen könnte man einfach primaryLabel als required (also ohne ?) in den Props angeben. Dann ist es immer da und diese Abfrage ist hinfällig

2021-07-30 09:30 UTC, klonsian commented on src/components/Modal/Modal.pcss
> +  content: "";
copy & paste von carbon. ich kanns probieren mal rauszunehmen.

2021-07-30 09:31 UTC, klonsian commented on src/components/Modal/Modal.pcss
> +    height: 100%;
würd ich im gleichen zug machen wie wir den rest aufräumen. :P

2021-07-30 09:31 UTC, klonsian commented on src/components/Modal/Modal.pcss
> +  @media screen and (max-width: $breakpoint-md) {
hab ich jetzt überall schon so drin. :D können wir gerne aber im Zuge des Aufräumens anfassen.

2021-07-30 09:33 UTC, klonsian commented on src/components/Modal/ModalFooter.tsx
> +      {((secondaryLabel && primaryLabel) || primaryLabel) && (
Ja, das ist noch n Relikt aus der Vorgängerversion. Da war primaryLabel optional. Da es jetzt im Footer ist, machst du den Footer ja nur, wenn du auch n Button platzieren willst.

2021-07-31 08:10 UTC, hendriku approved these changes

2021-07-31 08:11 UTC, merged